version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - revive
    - ineffassign
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: var-naming
        - name: indent-error-flow
  exclusions:
    presets: []
